### ISSUE TITLE
 SDK version >=2.16.2 <3.0.0, version solving failed

### ISSUE THREAD

**Issue by alperduzgun** [Mto292/json_parser#1]
Hello, 

`Because dop_nft_project depends on background_json_parser any which requires SDK version >=2.16.2 <3.0.0, version solving failed.
pub get failed (1; Because dop_nft_project depends on background_json_parser any which requires SDK version >=2.16.2 <3.0.0, version solving failed.)`

I am getting this error. Can you fix it?

**Comment by Mto292** [comment]
thx pro ı solved it.
